### ISSUE TITLE
Issue with Loading Huggingface Model Converted to ONNX

### ISSUE THREAD

**Issue by akameswa-cmu** [dakenf/diffusers.js#7]
Hi,
I converted a huggingface model following the article ['Accelerating Stable Diffusion Inference with ONNX Runtime'](https://medium.com/microsoftazure/accelerating-stable-diffusion-inference-with-onnx-runtime-203bd7728540). I am faced with the following error when I tried to load the model.

![image](https://github.com/dakenf/diffusers.js/assets/144072439/3b2b996a-4452-4447-bce0-24616697dc76)

But, I have renamed 'model.onnx.data' to 'match.onnx_data'. Could you please share the method you used to convert the huggingface models to the onnx format? Additionally, the modifications done to load the model correctly as well. Thanks!

**Comment by dakenf** [comment]
Hi! I've been using this script, but it has optimized settings for DML, so some changes for WebGPU are required https://github.com/Amblyopius/Stable-Diffusion-ONNX-FP16/blob/main/conv_sd_to_onnx.py
![](https://user-images.githubusercontent.com/7466130/281654236-4c0c11f8-6b90-4cfb-b1a1-8cab22cc91b4.png)
If you want to use the model with node/CPU you need to add last 4 lines (which disable Bias* kernels and packed KV/QKV)
If you plan to use it only with GPU then just last two, since packed KV/QKV are not supported on WebGPU

Filename for weights is adjusted on line 177. Please change it to `model.onnx_data`. I will think how to support various names, you cannot just rename it because target name is embedded into "model.onnx" file
<img width="445" alt="image" src="https://github.com/dakenf/diffusers.js/assets/7466130/ce983144-fcb8-4e71-8a6f-8fde1cbc8959">

I also plan to include a conversion script to next release to make it easier. To make it optimized for WebGPU and to support other models like latent consistency and SDXL

**Comment by akameswa-cmu** [comment]
Thanks for the fast response. The model generates an image when used through Node but not React. I can load the model, but it generates a 'black' output irrespective of the input parameters. The console shows no new error messages beyond those normally generated for LCM Dreamshaper FP16 (Works). All required files appear to have been downloaded based on the network tab. Please let me know how to resolve this problem.

**Comment by dakenf** [comment]
Please add --fp16 to conversion command, there is an issue with loading 32bit models I will try to resolve in next release of @aislamov/onnxruntime-web64

**Comment by akameswa-cmu** [comment]
I included the --fp16 argument during conversion.

**Comment by dakenf** [comment]
Can you tell which model you tried to convert? I can check it on the weekend

**Comment by akameswa** [comment]
Conversion mentioned in the [PR](https://github.com/dakenf/diffusers.js/pull/8#issue-1997219335) solved the problem. Had to add  **"--attention-slicing auto"** argument during conversion.
